import type {NextPage} from 'next'
import Head from 'next/head'
import styled from "styled-components";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <AppLayout>
        <AppHeader>Welcome</AppHeader>

        <AppMain>
          <h1>Welcome</h1>
          <div>Here are some content</div>
        </AppMain>

        <AppFooter>Legalities</AppFooter>
      </AppLayout>
    </>
  )
}

const AppLayout = styled.div`
  min-width: 100%;
  min-height: 100%;

  display: grid;
  grid-template-rows: 70px [row-main] minmax(0, 1fr) [row-footer] 80px;

  grid-template-columns: [col-start] 5fr 6fr 5fr [col-end];
  grid-template-areas:
      "header header header"
      ". main ."
      "footer footer footer";
`

const AppHeader = styled.header`
  background: blue;
  color: white;
  padding: 15px;
  grid-area: header;
  height: 100%;
`

const Navbar = styled.nav`
  display: flex;
  justify-content: space-between;
  align-items: center;

  height: 100%;
  border-bottom-width: 1px;
  border-bottom-style: solid;
`

const AppMain = styled.main`
  grid-area: main;
  background-color: white;
  padding: 15px 0 0 0;
  display: flex;
  flex-direction: column;
`

const AppFooter = styled.footer`
  background: blue;
  color: white;
  padding: 15px;
  grid-area: footer;
`

export default Home
